version: 2.1

# 実行するワークフローの定義
workflows:
  test-deploy:
    jobs:
      - test
 
# ワークフローの中で実行するジョブの定義
jobs:
  test:
    docker:
      - image: cimg/go:1.19.4
    steps:
      - checkout
      - run: go version
      - run: go env
      - run: go test
